# Connection Setup: 
# Name: VM
# Location: ROOT
# Protocol: RDP
# Hostname: IP of VM
# Port: 3389
# Username: Access local account first. 
# Password: Then switch login to Microsoft Account.
# Security mode: Any
# Ignore server certificate: Yes
# Time zone: Asia/Singapore
# Resize method: Reconnect
# Enable font smoothing (ClearType): Yes
#

services:
  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    volumes:
      - /mnt/sec/apps/guacamole/config:/config
    ports:
      - 3022:8080
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
#     networks:             # optional:
#       - windows_default   # to use the same network as windows-vm

# networks:
#   windows_default:
#     external: true
