services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: bridge  # Explicitly use bridge mode
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore
    volumes:
      - /mnt/sec/apps/jellyfin/config:/config
      - /mnt/sec/apps/jellyfin/cache:/cache
      - /mnt/sec/media:/media
    ports:
      - "3011:8096"
    devices:
      - /dev/dri:/dev/dri # iGPU
    cpus: "6"
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=true"