# Docker Compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this Docker Compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), MariaDB is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker compose pull'.
# - Run 'docker compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker compose up -d'.
# portainer: rename paperless-docker-compose.env to stack.env

services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-web
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "3019:8000"
    volumes:
      - /mnt/sec/apps/paperless/data:/usr/src/paperless/data
      - /mnt/sec/media/docs:/usr/src/paperless/media
      - /mnt/sec/apps/paperless/export:/usr/src/paperless/export
      - /mnt/sec/apps/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
    env_file:
      - stack.env
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  broker:
    image: docker.io/library/redis:8
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - /mnt/sec/apps/paperless/redisdata:/data
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
      
  db:
    image: docker.io/library/postgres:18
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - /mnt/sec/apps/paperless/pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
      
volumes:
  data:
  media:
  pgdata:
  redisdata: