services:
   vaultwarden:
      container_name: vaultwarden
      image: vaultwarden/server:latest
      volumes:
         - /mnt/sec/apps/vaultwarden/data/:/data/
      ports:
         - 3002:80
      restart: unless-stopped
      environment:
        - DOMAIN=https://domain.com
        - ADMIN_TOKEN=67B5C8DE5CC4956E0945E64A555155190B17219CBF925577CF9E0AD65625BF10
        - SMTP_HOST=smtp.zoho.com
        - SMTP_PORT=587
        - SMTP_FROM=username@email.com
        - SMTP_USERNAME=username@email.com
        - SMTP_PASSWORD=<email password>
        - SMTP_SECURITY=starttls
      security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
      labels:
         - "com.centurylinklabs.watchtower.enable=true"